// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

function sum(a, b) {
  return a + b | 0;
}

function sumFour(a, b, c, d) {
  return ((a + b | 0) + c | 0) + d | 0;
}

function sumThreePlus1(param, param$1, param$2) {
  return sumFour(1, param, param$1, param$2);
}

console.log((function (param) {
        return sumFour(1, 2, 3, param);
      }));

var mutableNum = /* record */[/* contents */2];

mutableNum[0] = 3;

var myRecord = /* record */[
  /* a */1,
  /* b */2
];

myRecord[/* b */1] = 4;

console.log(myRecord);

console.log(103);

var kid = /* Student */Block.__(1, ["John Doe"]);

var payload;

payload = typeof kid === "number" ? "Who are you?" : (
    kid.tag ? "Hey John Doe!" : "Hello Dr. John Doe"
  );

var array = /* :: */[
  1,
  /* [] */0
];

var attPM = array ? "Only 1 item" : "It's empty";

console.log(attPM);

var num = 1;

var kolya = /* record */[
  /* age */31,
  /* name */"Kolya"
];

var ilya = /* record */[
  /* age */21,
  /* name */"ilya"
];

var oldest = /* record */[
  /* age */103,
  /* name */"OLD",
  /* phone */"1234678"
];

exports.sum = sum;
exports.sumFour = sumFour;
exports.sumThreePlus1 = sumThreePlus1;
exports.num = num;
exports.mutableNum = mutableNum;
exports.myRecord = myRecord;
exports.kolya = kolya;
exports.ilya = ilya;
exports.oldest = oldest;
exports.kid = kid;
exports.payload = payload;
exports.array = array;
exports.attPM = attPM;
/*  Not a pure module */
